name: CI/CD – Node.js & Docker

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
      - run: npm ci && npm test

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug final IMAGE_NAME
        run: echo "DEBUG IMAGE_NAME=${{ env.IMAGE_NAME }}:latest"

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
